=== IBM/ibm-cos-sdk-js-v2/dependency-registry.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Dependency Registry Schema",
  "description": "Schema for the central dependency registry file",
  "type": "object",
  "required": ["dependencies", "devDependencies"],
  "properties": {
    "$schema": {
      "type": "string",
      "description": "JSON Schema reference"
    },
    "description": {
      "type": "string",
      "description": "Description of this registry file"
    },
    "dependencies": {
      "type": "object",
      "description": "Runtime dependencies used across workspace packages",
      "additionalProperties": {
        "type": "string",
        "pattern": "^[~^]?[0-9]+\\.[0-9]+\\.[0-9]+"
      }
    },
    "devDependencies": {
      "type": "object",
      "description": "Development dependencies used across workspace packages",
      "additionalProperties": {
        "type": "string",
        "pattern": "^[~^]?[0-9]+\\.[0-9]+\\.[0-9]+"
      }
    },
    "workspaceSpecificDevDependencies": {
      "type": "object",
      "description": "Configuration for workspace-specific dependencies",
      "properties": {
        "description": {
          "type": "string"
        },
        "allowed": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of dependencies that are allowed to be workspace-specific"
        }
      }
    }
  }
}

=== IBM/ibm-cos-sdk-js-v2/dependency-registry.json
{
  "$schema": "./dependency-registry.schema.json",
  "description": "Central registry for all external dependencies used across the monorepo. This is the single source of truth for dependency versions.",
  "dependencies": {
    "@aws-crypto/crc32": "^5.2.0",
    "@aws-crypto/crc32c": "^5.2.0",
    "@aws-crypto/sha1-browser": "^5.2.0",
    "@aws-crypto/sha256-browser": "^5.2.0",
    "@aws-crypto/sha256-js": "^5.2.0",
    "@aws-crypto/util": "^5.2.0",
    "@aws/lambda-invoke-store": "^0.2.2",
    "@smithy/abort-controller": "^4.2.8",
    "@smithy/config-resolver": "^4.4.6",
    "@smithy/core": "^3.21.0",
    "@smithy/credential-provider-imds": "^4.2.8",
    "@smithy/eventstream-serde-browser": "^4.2.8",
    "@smithy/eventstream-serde-config-resolver": "^4.3.8",
    "@smithy/eventstream-serde-node": "^4.2.8",
    "@smithy/fetch-http-handler": "^5.3.9",
    "@smithy/hash-blob-browser": "^4.2.9",
    "@smithy/hash-node": "^4.2.8",
    "@smithy/hash-stream-node": "^4.2.8",
    "@smithy/invalid-dependency": "^4.2.8",
    "@smithy/is-array-buffer": "^4.2.0",
    "@smithy/md5-js": "^4.2.8",
    "@smithy/middleware-content-length": "^4.2.8",
    "@smithy/middleware-endpoint": "^4.4.10",
    "@smithy/middleware-retry": "^4.4.26",
    "@smithy/middleware-serde": "^4.2.9",
    "@smithy/middleware-stack": "^4.2.8",
    "@smithy/node-config-provider": "^4.3.8",
    "@smithy/node-http-handler": "^4.4.8",
    "@smithy/property-provider": "^4.2.8",
    "@smithy/protocol-http": "^5.3.8",
    "@smithy/querystring-builder": "^4.2.8",
    "@smithy/shared-ini-file-loader": "^4.4.3",
    "@smithy/signature-v4": "^5.3.8",
    "@smithy/smithy-client": "^4.10.11",
    "@smithy/types": "^4.12.0",
    "@smithy/url-parser": "^4.2.8",
    "@smithy/util-base64": "^4.3.0",
    "@smithy/util-body-length-browser": "^4.2.0",
    "@smithy/util-body-length-node": "^4.2.1",
    "@smithy/util-config-provider": "^4.2.0",
    "@smithy/util-defaults-mode-browser": "^4.3.25",
    "@smithy/util-defaults-mode-node": "^4.2.28",
    "@smithy/util-endpoints": "^3.2.8",
    "@smithy/util-hex-encoding": "^4.2.0",
    "@smithy/util-middleware": "^4.2.8",
    "@smithy/util-retry": "^4.2.8",
    "@smithy/util-stream": "^4.5.10",
    "@smithy/util-utf8": "^4.2.0",
    "@smithy/util-waiter": "^4.2.8",
    "bowser": "^2.11.0",
    "aws-crt": ">=1.0.0",
    "buffer": "5.6.0",
    "events": "3.3.0",
    "fast-xml-parser": "5.7.3",
    "form-data": "^4.0.6",
    "ibm-cloud-sdk-core": "5.9.1",
    "stream-browserify": "3.0.0",
    "tslib": "^2.6.2"
  },
  "devDependencies": {
    "@commitlint/config-conventional": "17.0.2",
    "@microsoft/api-extractor": "7.52.7",
    "@rollup/plugin-json": "^6.1.0",
    "@rollup/plugin-node-resolve": "^16.0.3",
    "@rollup/plugin-typescript": "^12.1.4",
    "@tsconfig/recommended": "1.0.13",
    "@types/fs-extra": "^8.0.1",
    "@types/jsdom": "20.0.1",
    "@types/node": "^20.14.8",
    "@typescript-eslint/eslint-plugin": "5.55.0",
    "@typescript-eslint/parser": "5.55.0",
    "concurrently": "7.0.0",
    "decomment": "0.9.5",
    "downlevel-dts": "0.10.1",
    "esbuild": "0.25.0",
    "eslint": "8.36.0",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-prettier": "4.0.0",
    "eslint-plugin-simple-import-sort": "7.0.0",
    "eslint-plugin-sort-export-all": "1.2.2",
    "eslint-plugin-tsdoc": "0.2.17",
    "fastify": "^4.11.0",
    "fs-extra": "^9.0.0",
    "glob": "7.1.6",
    "json5": "^2.2.3",
    "lerna": "^8.1.8",
    "prettier": "2.8.5",
    "rimraf": "5.0.10",
    "rollup": "^4.59.0",
    "ts-loader": "9.4.2",
    "tsx": "4.19.2",
    "turbo": "2.9.14",
    "typescript": "~5.8.3",
    "vite": "^7.1.11",
    "vitest": "^4.0.17",
    "webpack": "5.101.0",
    "webpack-cli": "4.10.0",
    "yargs": "17.5.1"
  },
  "workspaceSpecificDevDependencies": {
    "description": "Dependencies that are allowed to be workspace-specific and don't need to be in the central registry",
    "allowed": [
      "premove",
      "web-streams-polyfill",
      "@tsconfig/node20"
    ]
  }
}
